version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - algafood-network
  
  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "240", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      CHAVE_ACESSO_S3: ${CHAVE_ACESSO_S3}
      CHAVE_ACESSO_SECRETA_S3: ${CHAVE_ACESSO_SECRETA_S3}
      NOME_BUCKET_S3_ALGAFOOD: ${NOME_BUCKET_S3_ALGAFOOD}
      BUCKET_S3_REGIAO: ${BUCKET_S3_REGIAO}
      DIRETORIO_IMG_ALGAFOOD_S3: ${DIRETORIO_IMG_ALGAFOOD_S3}
      HOST_EMAIL: ${HOST_EMAIL}
      USER_EMAIL: ${USER_EMAIL}
      PASSWORD_EMAIL: ${PASSWORD_EMAIL}
      FROM_EMAIL: ${FROM_EMAIL}
      SWAGGER_OAUTH_CLIENT_ID: ${SWAGGER_OAUTH_CLIENT_ID}
      SWAGGER_OAUTH_CLIENT_SECRET: ${SWAGGER_OAUTH_CLIENT_SECRET}
      JWT_KEYSTORE_PASSWORD: ${JWT_KEYSTORE_PASSWORD}
      JWT_KEYSTORE_KEYPAIR_ALIAS: ${JWT_KEYSTORE_KEYPAIR_ALIAS}
      LOGGLY_TOKEN: ${LOGGLY_TOKEN}
      JWT_KEYSTORE_JKS_LOCATION: 
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api